version: '2.28.1'

services:
  unibuds-api:
    container_name: node_backend
    build: .  
    ports:
      - "4000:4000"
    environment:
        - mongoURI=mongodb://mongo:27017/mydatabase
        - JWT_HASH=averysecurehash
    links:
      - mongo  

  mongo:
    container_name: mongodb_container
    build: /data/. 
    ports:
       - "27017:27017"


     