export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_PENDING = "GET_CHATS_PENDING";

export const SET_SEND_MESSAGE_PENDING = "SET_SEND_MESSAGE_PENDING";
export const SET_SEND_MESSAGE_SUCCESS = "SET_SEND_MESSAGE_SUCCESS"; 

export const SET_MESSAGE_RECIEVED = "SET_MESSAGE_RECIEVED";