export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";

export const SET_PROFILE_SUCCESS  = "SET_PROFILE_SUCCESS";
export const SET_PROFILE_FAIL  = "SET_PROFILE_FAIL";