export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_PENDING = "GET_USER_PENDING";

export const SET_USER_PENDING  = "SET_USER_PENDING";
export const SET_USER_SUCCESS  = "SET_USER_SUCCESS";
export const SET_USER_FAIL  = "SET_USER_FAIL";